version: '3.9'

services:

  api1: &ap1 
    image: bookstore
    volumes:
      - ./app:/app
    networks:
      - backend
    env_file:
      - ./.env.dev
    depends_on:
      - db
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1GB'

  api2:
    <<: *ap1


  db:
    image: postgres:13.0-alpine
    ports:
      - '5432:5432'  # Porta padrão do PostgreSQL
    networks:
      - backend
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: bookstore_dev
      POSTGRES_PASSWORD: bookstore_dev
      POSTGRES_DB: db
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '1.8GB'

  nginx:
    image: nginx:latest
    volumes:
      - './app/static:/app/static'
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80' 
    networks:
      - backend
    depends_on:
      - api1
      - api2
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '256MB'

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
